config/routes.rb
Rails.application.routes.draw do
	root                    to: 'static_pages#home',       as: :home

	get 'contact',		    to: 'static_pages#contact',    as: :contact
	get 'about', 		    to: 'static_pages#about', 	   as: :about
	get 'about/toi',        to: 'static_pages#toi',        as: :you
	get 'about/ton_groupe', to: 'static_pages#ton_groupe', as: :yourgroup

	get  'users/new',		to: 'users#new',               as: :newuser
	post 'users/create',    to: 'users#create'           

	get 'users/error', 		to: 'users#error',             as: :error
	get 'users/:user_id',   to: 'users#show',			   as: :showprofil


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	#obligation d'avoir un nom avec le nombre de caractere definie 
    validates :username, presence: true, length:{minimum: 3, maximum: 25}
    
    #obligation d'avoire une bio avec le nombre de caractere definie 
    validates :bio,  presence: true, length:{minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def toi
  end 

  def ton_groupe
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new 
		@user = User.new
	end 

	def create
		@user = User.new
		@user.username = params[:username]
		@user.bio = params[:bio]

        if @user.save
            redirect_to "/users/#{@user.id}"
        else
            redirect_to "/users/error"
        end
	end 

	def show
		@user = User.find(params[:user_id])

		@username = @user.username
		@userbio  = @user.bio
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p><%= link_to 'Acceuil', home_path %></p>
<p><%= link_to 'toi', you_path %></p>
<p><%= link_to 'ton_groupe', yourgroup_path %></p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Bienvenue sur mon site ⛵️🎓😇 lol mdr 😇❤️😻</h1>

<p><%= link_to 'About', about_path %></p>
<p>Pour créer un utilisateur, <%= link_to  'c\'est par ici', newuser_path %></p> 

app/views/static_pages/toi.html.erb
<h1>YOU an only YOU</h2>

<p>Revenir sur <%= link_to 'About', about_path %></p>

app/views/static_pages/ton_groupe.html.erb
<h1>ton groupe</h1>

<p>Revenir sur <%= link_to 'About', about_path %></p>

app/views/users/error.html.erb
<h1>Verifie que tes coordonné respectent les conditions suivante</h1>
	<ul>
		<li>ton username a bien plus de 3 caracteres</li>
		<li>ta bio a bien plus de 10 caracteres</li>

	</ul>

app/views/users/new.html.erb
<h1>Bienvenue dans la création d'utilisateurs !</h1>

<form action="/users/create" method="post">

	<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    Username: <input name="username" type="text"><br>

    Bio:      <textarea name="bio" rows="4" cols="50"> </textarea><br>
              <input type="submit" value="Submit">
</form>

app/views/users/show.html.erb
<h1> Bienvenue @<%= @username  %>! </h1>

<h3>Voici ta bio trop cool : </h3>
<p><%= @userbio %></p>